version: '3.4'

services:
  semasio_challenge_2:
    image: ${DOCKER_REGISTRY-}semasiochallenge2
    build:
      context: .
      dockerfile: Dockerfile
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
        - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
        - "27017:27017"

  web:
    build:
        context: .
    ports:
        - "8000:80"
        - "44348:443"
    depends_on:
        - mongo
    volumes:
        - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
    links:
        - mongo